markdown: rdiscount
permalink: /:title/
url: http://hogwartsrico.github.io/
name: Rico's Blog
author: Rico
qq: 359101562
email: chenhongjie101@gmail.com
duoshuo: yonsm
beian: 浙ICP备12026616号
cnzz: 1000154360
weibo: 1878017080
github: hogwartsrico
pygments: true
safe: true
paginate: 20
about: "这里是 Rico 的个人博客，创建于 2013 年。<br/>这里包含了部分个人的“折腾”过程、结论和成果，切换到分类模可以更快地找到感兴趣的内容，欢迎观赏、建议、拍砖……"
